spring:
  application:
    name: library-service
  security:
    users:
      - name: library
        password: 4815162342
        roles: USER, ADMIN
      - name: user_1
        password: user_pass_1
        roles: USER
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${spring.datasource.username}
    username: ${DATABASE_USER:test_user_1}
    password: ${DATABASE_PASSWORD:test_pass_1}
server:
  port: ${APPLICATION_PORT:8082}
logging:
  level:
    org.zalando.logbook: TRACE
logbook:
  predicate:
    include:
      - path: /api/**
        methods:
          - GET
          - POST
library-service:
  booking:
    default-period-days: 30